<a href="https://colab.research.google.com/github/Abhi-3026/AI_ML_AVEN/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Array by Passing Tuple

In [ ]:
import numpy as np

In [ ]:
n = np.array((1,2,3,4,5))
print(n)
print(type(n))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Numpy Array by Passing List

In [ ]:
m = np.array([1,2,3,4,5])
print(m)
print(type(m))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions in Numpy Array

In [ ]:
# no dimensional array
n = np.array(25)
print(n)
print("Dimensions = ", n.ndim)

25
Dimensions =  0


In [ ]:
# One dimensional array
n = np.array([10,20,30,40,50])
print(n)
print("Dimensions = ", n.ndim)

[10 20 30 40 50]
Dimensions =  1


In [ ]:
# Two dimensional array
n = np.array([[10,20,30],[40,50,60]])
print(n)
print("Dimensions = ", n.ndim)

[[10 20 30]
 [40 50 60]]
Dimensions =  2


In [ ]:
#three dimensional array
n= np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(n)
print("Dimensions = ", n.ndim)


[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
Dimensions =  3


Intialize Numpy Arrays

In [ ]:
import numpy as np

n = np.zeros([2,3])
print(n)

[[0. 0. 0.]
 [0. 0. 0.]]


**DATATYPES**

In [ ]:
# Get the datatype of a Numpy Arrays with Integers
import numpy as np

n = np.array([1,2,3,4,5])
print(n.dtype)

int64


In [ ]:
# Get the datatype of a Numpy Arrays with Strings
n = np.array(["abhi","anu","arun","prince","rishu"])
print(n)
print(n.dtype)

['abhi' 'anu' 'arun' 'prince' 'rishu']
<U6


In [ ]:
import numpy as np

n = np.array(["abhi","anu","arun","prince","rishu"], dtype = "S5")
print(n)
print(n.dtype)


[b'abhi' b'anu' b'arun' b'princ' b'rishu']
|S5


In [ ]:
# Convert one datatype to another
import numpy as np

n = np.array([1,2,3,4,5])
print(n)
print(n.dtype)

new = n.astype("f")
print(new)
print(new.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float32


**INDEXING**

In [ ]:
# Accessing the 1st element (index 0) from an 1d Array
import numpy as np

n = np.array([1,2,3,4,5])
print(n[0])

# Accessing the 4th element (index 0 ) from a 1d array

print(n[3])

1
4


In [ ]:
# Accessing the elements in 2d array
n = np.array([[1,2,3],[4,5,6]])
print(n)
print(n[0,0])
print(n[0,1])
print(n[1,0])
print(n[1,1])

[[1 2 3]
 [4 5 6]]
1
2
4
5


In [ ]:
# Creating a 3D array (list of lists of lists)
array_3d = [[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]
print(array_3d)
# Accessing elements
# Access the element in the first row, first column, first depth (1)
element_1 = array_3d[0][0][0]
print(element_1)  # Output: 1

# Access the element in the second row, second column, third depth (12)
element_2 = array_3d[1][1][2]
print(element_2)  # Output: 12


[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
1
12


In [ ]:
# NEGATIVE INDEXING
# USING 1D ARRAY
n = np.array([1,2,3,4,5])
print(n[-1])

# USING 2D ARRAY
n = np.array([[1,2,3],[4,5,6]])
print(n[0,-1])

5
3


In [ ]:
# Creating a 3D array (list of lists of lists)
array_3d = [[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]

# Accessing elements using negative indexing
# Access the element in the last row, last column, last depth (12)
element_1 = array_3d[-1][-1][-1]
print(element_1)  # Output: 12

# Access the element in the first row, last column, last depth (6)
element_2 = array_3d[0][-1][-1]
print(element_2)  # Output: 6

# Access the element in the last row, first column, first depth (7)
element_3 = array_3d[-1][0][0]
print(element_3)  # Output: 7


12
6
7


**SLICING**

In [ ]:
#Slicing from index 1 to 3 (3 excluded)
import numpy as np

n = np.array([1,2,3,4,5,6,7,8,9,10])
print(n[1:3])

# Slicing from index 2 to 5 (5 exclude)
n = np.array([1,2,3,4,5,6,7,8,9,10])
print(n[2:5])

# Slicing from index 5 to Last
n = np.array([1,2,3,4,5,6,7,8,9,10])
print(n[5:])

# Slicing from beginning to index 5 (5 is excluded)
n = np.array([1,2,3,4,5,6,7,8,9,10])
print(n[:5])

[2 3]
[3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]


Slicing 1D Array

In [ ]:
import numpy as np

n = np.array([1,2,3,4,5,6,7,8,9,10])
print(n[1:8:2])

[2 4 6 8]


Slicing 2D Array

In [ ]:
n = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(n)
print(n[1,1:4])

#Slicing the both dimensions in array
n = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(n[0:2,2:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[[ 3  4  5]
 [ 8  9 10]]


**NUMPY ARRAY SHAPE**

Zero dimesional array

In [ ]:
# Check the shape of zero- dimensional array
n = np.array(25)
print(n)
print(n.ndim)
print(n.shape)

25
0
()


Shape of a 1D array

In [ ]:
n = np.array([1,2,3,4,5])
print(n)
print(n.ndim)
print(n.shape)

[1 2 3 4 5]
1
(5,)


Shape of 2D array

In [ ]:
n = np.array([[1,2,3],[4,5,6]])
print(n)
print(n.ndim)
print(n.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


Shape of 3D dimensional array

In [ ]:
n = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n)
print(n.ndim)
print(n.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


**RESHAPE**

In [ ]:
# Reshaping 1D array to 2D array
import numpy as np

n = np.array([1,2,3,4,5,6,7,8,9,10])
print("One dimensional array = ", n)

#Reshape
resarr = n.reshape(2,5)
print("Reshaped array = ", resarr)

One dimensional array =  [ 1  2  3  4  5  6  7  8  9 10]
Reshaped array =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Reshaping 3D to 1D array

n = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D array = ", n)

#Reshape
resarr = n.reshape(-1)
print("Reshaped array = ", resarr)

3D array =  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Reshaped array =  [ 1  2  3  4  5  6  7  8  9 10 11 12]


**ITERATE NUMPY ARRAY**S

In [ ]:
# Iterate 1D array
import numpy as np
n = np.array([1,2,3,4,5,6])
print("Iterating\n")
for i in n:
  print(i)

print("Type = ", type(n))
print("Datatype =", type(n.dtype))
print("Dimensions = ", n.ndim)
print("Shape = ", n.shape)

Iterating

1
2
3
4
5
6
Type =  <class 'numpy.ndarray'>
Datatype = <class 'numpy.dtypes.Int64DType'>
Dimensions =  1
Shape =  (6,)


In [ ]:
# Iterate 2D array
import numpy as np
n = np.array([[1,2,3],[4,5,6]])
print("Iterating\n")
for i in n:
  print(i)

print("Type = ", type(n))
print("Datatype =", type(n.dtype))
print("Dimensions = ", n.ndim)
print("Shape = ", n.shape)

Iterating

[1 2 3]
[4 5 6]
Type =  <class 'numpy.ndarray'>
Datatype = <class 'numpy.dtypes.Int64DType'>
Dimensions =  2
Shape =  (2, 3)


In [ ]:
# Iterate 3D array
import numpy as np
n = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Iterating\n")
for i in n:
  print(i)

print("Type = ", type(n))
print("Datatype =", type(n.dtype))
print("Dimensions = ", n.ndim)
print("Shape = ", n.shape)

Iterating

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Type =  <class 'numpy.ndarray'>
Datatype = <class 'numpy.dtypes.Int64DType'>
Dimensions =  3
Shape =  (2, 2, 3)


**JOINING NUMPY ARRAYS**

1. Concatenate() method

In [ ]:
import numpy as np

n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])

print("Iterating array 1")
for i in n1:
  print(i)

print("Iterating array 2")
for i in n2:
  print(i)

# Concatenate
resarr = np.concatenate((n1,n2))
print("Concatenated array = ",resarr)
print(i)

Iterating array 1
1
2
3
4
5
Iterating array 2
6
7
8
9
10
Concatenated array =  [ 1  2  3  4  5  6  7  8  9 10]
10


2. Stack method

In [ ]:
import numpy as np

n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])

print("Iterating array 1")
for i in n1:
  print(i)

print("Iterating array 2")
for i in n2:
  print(i)

resarr = np.stack((n1,n2))
print("Stack array = ",resarr)


Iterating array 1
1
2
3
4
5
Iterating array 2
6
7
8
9
10
Stack array =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


i. hstack()

In [ ]:
import numpy as np

n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])

print("Iterating array 1")
for i in n1:
  print(i)

print("Iterating array 2")
for i in n2:
  print(i)

resarr = np.hstack((n1,n2))
print("After joining along rows =\n",resarr)

Iterating array 1
1
2
3
4
5
Iterating array 2
6
7
8
9
10
After joining along rows =
 [ 1  2  3  4  5  6  7  8  9 10]


ii. Vstack()

In [ ]:
import numpy as np

n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])

print("Iterating array 1")
for i in n1:
  print(i)

print("Iterating array 2")
for i in n2:
  print(i)

resarr = np.vstack((n1,n2))
print("After joining along columns =\n",resarr)

Iterating array 1
1
2
3
4
5
Iterating array 2
6
7
8
9
10
After joining along columns =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


iii. dstack

In [ ]:
import numpy as np

n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])

print("Iterating array 1")
for i in n1:
  print(i)

print("Iterating array 2")
for i in n2:
  print(i)

resarr = np.dstack((n1,n2))
print("After joining along depth =\n",resarr)

Iterating array 1
1
2
3
4
5
Iterating array 2
6
7
8
9
10
After joining along depth =
 [[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


iv. Column_stack

In [ ]:
import numpy as np

n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])

print("Iterating array 1")
for i in n1:
  print(i)

print("Iterating array 2")
for i in n2:
  print(i)

resarr = np.column_stack((n1,n2))
print("After joining along columns =\n",resarr)

Iterating array 1
1
2
3
4
5
Iterating array 2
6
7
8
9
10
After joining along columns =
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


**SPLIT NUMPY_ARRAY**

In [ ]:
# Split 1D array in numpy
import numpy as np

n = np.array([1,2,3,4,5,6,7,8,9,10])
print("Iterating Array....")
for a in n:
  print(a)

resarr = np.array_split(n,5)
print("Splitted array = ",resarr)

for a in resarr:
  print(a)

Iterating Array....
1
2
3
4
5
6
7
8
9
10
Splitted array =  [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [ ]:
# Access a split 1D array in NUMPY
import numpy as np

n = np.array([1,2,3,4,5,6,7,8,9,10])
print("Iterating Array....")
for a in n:
  print(a)

resarr = np.array_split(n,5)
print("\n Access splitted array individually...")
print(  resarr[0]  )
print(  resarr[1]  )
print(  resarr[2]  )
print(  resarr[3]  )
print(  resarr[4]  )

Iterating Array....
1
2
3
4
5
6
7
8
9
10

 Access splitted array individually...
[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [ ]:
# split a 2D array in numpy and access it
import numpy as np

n = np.array([[1, 3, 5],[4, 8, 12]])
print("Iterating Array....")
for a in n:
  print(a)

resarr = np.array_split(n,2)
print(resarr)

print("\n Access splitted array individually...")
print(resarr[0])
print(resarr[1])

Iterating Array....
[1 3 5]
[ 4  8 12]
[array([[1, 3, 5]]), array([[ 4,  8, 12]])]

 Access splitted array individually...
[[1 3 5]]
[[ 4  8 12]]


**Search a Numpy Array for a** **Value**

In [ ]:
import numpy as np
n = np.array([10, 20, 30, 40, 50, 30])

print("Iterating Array....")
for a in n:
  print(a)

resarr = np.where(n == 30)
print("Index of 30 = ",resarr)

Iterating Array....
10
20
30
40
50
30
Index of 30 =  (array([2, 5]),)


**SORTING**

In [ ]:
# Sort a 1D Integer Array in Numpy
import numpy as np

n = np.array([50, 25, 35, 15, 55, 75, 65, 60, 30, 45])

print("Iterating Array....")
for a in n:
  print(a)

resarr = np.sort(n)
print("Sorted array = ",resarr)

Iterating Array....
50
25
35
15
55
75
65
60
30
45
Sorted array =  [15 25 30 35 45 50 55 60 65 75]


In [ ]:
# Sort a 1D String Array in Numpy
import numpy as np

n = np.array(["abhi","anu","arun","prince","rishu"])

print("Iterating Array....")
for a in n:
  print(a)

resarr = np.sort(n)
print("Sorted array = ",resarr)

Iterating Array....
abhi
anu
arun
prince
rishu
Sorted array =  ['abhi' 'anu' 'arun' 'prince' 'rishu']


In [ ]:
# Sort a 2D array in numpy
import numpy as np
n = np.array([[1, 5, 7],[4, 24, 12]])
print("Iterating Array....")
for a in n:
  print(a)

resarr = np.sort(n)
print("Sorted array = ",resarr)

Iterating Array....
[1 5 7]
[ 4 24 12]
Sorted array =  [[ 1  5  7]
 [ 4 12 24]]


**AXES IN NUMPY ARRAYS**

In [ ]:
#Get the Minimum value with axes in Numpy
import numpy as np

n = np.array([[1, 5, 7],[4, 24, 12],[100, 200, 300]])
print("Iterating 2D Array....")
for a in n:
  print(a)

resarr = np.min(n, axis=0)
print("Minimum value with axes 0 (vertical axes) = ",resarr)

resarr = np.min(n, axis=1)
print("Minimum value with axes 1 (Horizontal axes) = ",resarr)

Iterating 2D Array....
[1 5 7]
[ 4 24 12]
[100 200 300]
Minimum value with axes 0 (vertical axes) =  [1 5 7]
Minimum value with axes 1 (Horizontal axes) =  [  1   4 100]


**INTERSECTION OF NUMPY ARRAYS**

In [ ]:
#Intersection Between Two Sorted Arrays
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Iterating Array 1....")
for a in n1:
  print(a)

print("Iterating Array 2....")
for a in n2:
  print(a)

resarr = np.intersect1d(n1,n2)
print("Intersection of two arrays = ",resarr)

Iterating Array 1....
1
2
3
4
5
Iterating Array 2....
3
4
5
6
7
Intersection of two arrays =  [3 4 5]


In [ ]:
#Intersection between two Unsorted Arrays
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Iterating Array 1....")
for a in n1:
  print(a)

print("Iterating Array 2....")
for a in n2:
  print(a)


resarr = np.intersect1d(n1,n2, assume_unique=True)
print("Intersection of two arrays = ",resarr)

Iterating Array 1....
1
2
3
4
5
Iterating Array 2....
3
4
5
6
7
Intersection of two arrays =  [3 4 5]


In [ ]:
# Intersection between Numpy Arrays with different elements
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([6, 7, 8, 9, 10])

print("Iterating Array 1....")
for a in n1:
  print(a)

print("Iterating Array 2....")
for a in n2:
  print(a)

resarr = np.intersect1d(n1,n2, assume_unique=True)
print("Intersection of two arrays = ",resarr)


Iterating Array 1....
1
2
3
4
5
Iterating Array 2....
6
7
8
9
10
Intersection of two arrays =  []


**DIFFERENCE BETWEEN NUMPY ARRAYS**

In [ ]:
# Find the between two arrays
import numpy as np

n1 = np.array([1, 2, 3, 4, 5, 10])
n2 = np.array([3, 4, 5, 6, 7, 20])

print("Iterating Array 1....")
for a in n1:
  print(a)

print("Iterating Array 2....")
for a in n2:
  print(a)

resarr = np.setdiff1d(n1,n2)
print("\nDifference = \n",resarr)


Iterating Array 1....
1
2
3
4
5
10
Iterating Array 2....
3
4
5
6
7
20

Difference = 
 [ 1  2 10]


In [ ]:
# Find the difference between two arrays(n2-n1)
import numpy as np

n1 = np.array([1, 2, 3, 4, 5, 10])
n2 = np.array([3, 4, 5, 6, 7, 20])

print("Iterating Array 1....")
for a in n1:
  print(a)

print("Iterating Array 2....")
for a in n2:
  print(a)

resarr = np.setdiff1d(n2,n1)
print("\nDifference = \n",resarr)

Iterating Array 1....
1
2
3
4
5
10
Iterating Array 2....
3
4
5
6
7
20

Difference = 
 [ 6  7 20]


**ARTHEMATIC OPERATORS**

1. ADDITION

In [ ]:
# Add the elements of numpy arrays
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

resarr = np.add(n1,n2)
print("Addition of two arrays = ",resarr)

# ADD THE COLUMN VALUES OF NUMPY
n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

resarr = np.sum([n1,n2], axis = 0)
print("Addition of two arrays = ",resarr)

# Add the individual array values using the axes parameter
n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

resarr = np.sum([n1,n2], axis = 1)
print("Addition of two arrays = ",resarr)


Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Addition of two arrays =  [ 4  6  8 10 12]
Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Addition of two arrays =  [ 4  6  8 10 12]
Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Addition of two arrays =  [15 25]


2. SUBSTRACTION

In [ ]:
# SUBSTRACT NUMPY ARRAYS
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

resarr = np.subtract(n1,n2)
print("Subtraction of two arrays = ",resarr)


Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Subtraction of two arrays =  [-2 -2 -2 -2 -2]


3. MULTIPLICATION

In [ ]:
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

resarr = np.multiply(n1,n2)
print("Multiplication of two arrays = ",resarr)

Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Multiplication of two arrays =  [ 3  8 15 24 35]


4. DIVISION

In [ ]:
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

resarr = np.divide(n1,n2)
print("Division of two arrays = ",resarr)

Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Division of two arrays =  [0.33333333 0.5        0.6        0.66666667 0.71428571]


**SCALAR OPERATIONS**

1. ADDITION

In [ ]:
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = n1 + 100
n2 = n2 + 200

print("Array1 Updated = ",n1)
print("Array2 Updated = ",n2)

Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Array1 Updated =  [101 102 103 104 105]
Array2 Updated =  [203 204 205 206 207]


2. SUBSTRACTION

In [ ]:
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = n1 - 1
n2 = n2 - 2

print("Array1 Updated = ",n1)
print("Array2 Updated = ",n2)

Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Array1 Updated =  [0 1 2 3 4]
Array2 Updated =  [1 2 3 4 5]


3. MULTIPLICATION

In [ ]:
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = n1 * 100
n2 = n2 * 200

print("Array1 Updated = ",n1)
print("Array2 Updated = ",n2)

Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Array1 Updated =  [100 200 300 400 500]
Array2 Updated =  [ 600  800 1000 1200 1400]


4. DIVISION

In [ ]:
import numpy as np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([3, 4, 5, 6, 7])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = n1 / 3
n2 = n2 / 7

print("Array1 Updated = ",n1)
print("Array2 Updated = ",n2)

Array1 =  [1 2 3 4 5]
Array2 =  [3 4 5 6 7]
Array1 Updated =  [0.33333333 0.66666667 1.         1.33333333 1.66666667]
Array2 Updated =  [0.42857143 0.57142857 0.71428571 0.85714286 1.        ]


**STATISTICAL OPERATIONS**

1. MEAN

In [ ]:
import numpy as np

n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = np.mean(n1)
n2 = np.mean(n2)

print("Mean of array1 = ",n1)
print("Mean of array2 = ",n2)

resarr = np.mean([n1,n2])
print("Mean of two arrays = ",resarr)

Array1 =  [15 20 25 30]
Array2 =  [65 75 85 95]
Mean of array1 =  22.5
Mean of array2 =  80.0
Mean of two arrays =  51.25


2. MEDIAN

In [ ]:
import numpy as np

n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = np.median(n1)
n2 = np.median(n2)

print("Median of array1 = ",n1)
print("Median of array2 = ",n2)

Array1 =  [15 20 25 30]
Array2 =  [65 75 85 95]
Median of array1 =  22.5
Median of array2 =  80.0


3. STANDARD DEVIATION

In [ ]:
import numpy as np

n1 = np.array([15, 20, 25, 30])
n2 = np.array([65, 75, 85, 95])

print("Array1 = ",n1)
print("Array2 = ",n2)

n1 = np.std(n1)
n2 = np.std(n2)

print("Standard Deviation of array1 = ",n1)
print("Standard Deviation of array2 = ",n2)

Array1 =  [15 20 25 30]
Array2 =  [65 75 85 95]
Standard Deviation of array1 =  5.5901699437494745
Standard Deviation of array2 =  11.180339887498949


**RANDOM NUMBER**

In [ ]:
# Generate a random number
from numpy import random

n = random.randint(100)
print("Random NUmber = ",n)

# Random number with a fixed size
from numpy import random

n = random.randint(100, size=(5))
print("Random NUmber = ",n)

# Generate one of the random values based on an array of values
from numpy import random

n = random.choice([1,2,3,4,5])
print("Random NUmber = ",n)

Random NUmber =  72
Random NUmber =  [42 88 55 22 21]
Random NUmber =  5


**NUMPY LOGS**

1. LOG BASE 2

In [ ]:
import numpy as np

n = np.array([1, 2, 3, 4, 5])
print("Array = ",n)

n = np.log2(n)
print("Log base 2 = ",n)

Array =  [1 2 3 4 5]
Log base 2 =  [0.         1.         1.5849625  2.         2.32192809]


2. LOG BASE 10

In [ ]:
import numpy as np

n = np.array([1, 2, 3, 4, 5])
print("Array = ",n)

n = np.log10(n)
print("Log base 10 = ",n)

Array =  [1 2 3 4 5]
Log base 10 =  [0.         0.30103    0.47712125 0.60205999 0.69897   ]


**NUMPY - LCM & HCF**

1. LCM

In [ ]:
import numpy as np

a = 3
b = 6

n = np.lcm(a,b)
print("LCM of a and b = ",n)

LCM of a and b =  6


2. HCF/GCD

In [ ]:
import numpy as np

a = 3
b = 6

n = np.gcd(a,b)
print("GCD of a and b = ",n)

GCD of a and b =  3
